# Generated by Django 4.1.7 on 2023-05-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coingecko', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='ath',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='ath_change_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='ath_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='atl',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='atl_change_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='atl_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='circulating_supply',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='current_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='high_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='low_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='market_cap',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='market_cap_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='market_cap_change_percentage_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='market_cap_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='price_change_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='price_change_percentage_24h',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='total_supply',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='total_volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
