# Generated by Django 4.1.7 on 2023-05-27 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coingecko', '0002_coin_ath_coin_ath_change_percentage_coin_ath_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinsModel',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('image', models.URLField(blank=True, null=True)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('market_cap_rank', models.IntegerField(blank=True, null=True)),
                ('total_volume', models.FloatField(blank=True, null=True)),
                ('high_24h', models.FloatField(blank=True, null=True)),
                ('low_24h', models.FloatField(blank=True, null=True)),
                ('price_change_24h', models.FloatField(blank=True, null=True)),
                ('price_change_percentage_24h', models.FloatField(blank=True, null=True)),
                ('market_cap_change_24h', models.FloatField(blank=True, null=True)),
                ('market_cap_change_percentage_24h', models.FloatField(blank=True, null=True)),
                ('circulating_supply', models.FloatField(blank=True, null=True)),
                ('total_supply', models.FloatField(blank=True, null=True)),
                ('ath', models.FloatField(null=True)),
                ('ath_change_percentage', models.FloatField(null=True)),
                ('ath_date', models.DateTimeField(null=True)),
                ('atl', models.FloatField(null=True)),
                ('atl_change_percentage', models.FloatField(null=True)),
                ('atl_date', models.DateTimeField(null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Coin',
        ),
    ]
