# Generated by Django 4.1.7 on 2023-05-27 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coingecko', '0003_coinsmodel_delete_coin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoinsModel',
            new_name='Coin',
        ),
        migrations.CreateModel(
            name='HodlCoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coingecko.coin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
