# Generated by Django 4.1.7 on 2023-05-28 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coingecko', '0005_alter_coin_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('market_cap', models.IntegerField(blank=True, null=True)),
                ('market_cap_change_percentage_24h', models.FloatField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('top3coins', models.URLField(blank=True, null=True)),
                ('volume_24h', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
